const users = [
{ name: "User1", email: "user1@example.com" },
{ name: "User2", email: "user2@example.com" },
{ name: "User3", email: "user3@example.com" },
{ name: "User4", email: "user4@example.com" },
{ name: "User5", email: "user5@example.com" },
{ name: "User6", email: "user6@example.com" },
{ name: "User7", email: "user7@example.com" },
{ name: "User8", email: "user8@example.com" },
{ name: "User9", email: "user9@example.com" },
{ name: "User10", email: "user10@example.com" },
{ name: "User11", email: "user11@example.com" },
{ name: "User12", email: "user12@example.com" },
{ name: "User13", email: "user13@example.com" },
{ name: "User14", email: "user14@example.com" },
{ name: "User15", email: "user15@example.com" },
{ name: "User16", email: "user16@example.com" },
{ name: "User17", email: "user17@example.com" },
{ name: "User18", email: "user18@example.com" },
{ name: "User19", email: "user19@example.com" },
{ name: "User20", email: "user20@example.com" },
{ name: "User21", email: "user21@example.com" },
{ name: "User22", email: "user22@example.com" },
{ name: "User23", email: "user23@example.com" },
{ name: "User24", email: "user24@example.com" },
{ name: "User25", email: "user25@example.com" },
{ name: "User26", email: "user26@example.com" },
{ name: "User27", email: "user27@example.com" },
{ name: "User28", email: "user28@example.com" },
{ name: "User29", email: "user29@example.com" },
{ name: "User30", email: "user30@example.com" },
{ name: "User31", email: "user31@example.com" },
{ name: "User32", email: "user32@example.com" },
{ name: "User33", email: "user33@example.com" },
{ name: "User34", email: "user34@example.com" },
{ name: "User35", email: "user35@example.com" },
{ name: "User36", email: "user36@example.com" },
{ name: "User37", email: "user37@example.com" },
{ name: "User38", email: "user38@example.com" },
{ name: "User39", email: "user39@example.com" },
{ name: "User40", email: "user40@example.com" },
{ name: "User41", email: "user41@example.com" },
{ name: "User42", email: "user42@example.com" },
{ name: "User43", email: "user43@example.com" },
{ name: "User44", email: "user44@example.com" },
{ name: "User45", email: "user45@example.com" },
{ name: "User46", email: "user46@example.com" },
{ name: "User47", email: "user47@example.com" },
{ name: "User48", email: "user48@example.com" },
{ name: "User49", email: "user49@example.com" },
{ name: "User50", email: "user50@example.com" },
{ name: "User496", email: "user496@example.com" },
{ name: "User497", email: "user497@example.com" },
{ name: "User498", email: "user498@example.com" },
{ name: "User499", email: "user499@example.com" },
{ name: "User500", email: "user500@example.com" }
];







module.exports = {users};